language: node_js
dist: bionic
arch: amd64
cache: npm
os:
  - linux
  - osx
  - windows
node_js:
  - 15
  - 14
  - 13
  - 12
  - 11
  - 10
install:
  - npm install
script:
  - npm run build
  - npm run test
